{
 "title": "ABS",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Wheels_DiskTemperature (°C)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "\"hawkbitDevice\"",
     "measure": "HawkbitDevice001",
     "rawQuery": "SELECT Wheel1_DiskTemperature, Wheel2_DiskTemperature, Wheel3_DiskTemperature, Wheel4_DiskTemperature, time FROM $__database.$__table WHERE time BETWEEN from_milliseconds($__from) AND from_milliseconds($__to)",
     "table": "\"ABS\""
    }
   ]
  },
  {
   "title": "Wheels_FluidTemperature (°C)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "database": "\"hawkbitDevice\"",
     "measure": "HawkbitDevice001",
     "rawQuery": "SELECT Wheel1_FluidTemperature, Wheel2_FluidTemperature, Wheel3_FluidTemperature, Wheel4_FluidTemperature, time FROM $__database.$__table WHERE time BETWEEN from_milliseconds($__from) AND from_milliseconds($__to)",
     "table": "\"ABS\""
    }
   ]
  },
  {
   "title": "Wheels_DiskTemperature (°C)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "database": "\"hawkbitDevice\"",
     "measure": "HawkbitDevice001",
     "rawQuery": "SELECT Wheel1_DiskTemperature, Wheel2_DiskTemperature, Wheel3_DiskTemperature, Wheel4_DiskTemperature, time FROM $__database.$__table WHERE time BETWEEN from_milliseconds($__from) AND from_milliseconds($__to)",
     "table": "\"ABS\""
    }
   ]
  },
  {
   "title": "Wheels_FluidTemperature (°C)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "database": "\"hawkbitDevice\"",
     "measure": "HawkbitDevice001",
     "rawQuery": "SELECT Wheel1_FluidTemperature, Wheel2_FluidTemperature, Wheel3_FluidTemperature, Wheel4_FluidTemperature, time FROM $__database.$__table WHERE time BETWEEN from_milliseconds($__from) AND from_milliseconds($__to)",
     "table": "\"ABS\""
    }
   ]
  },
  {
   "title": "BrakePressure (Pa)",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "database": "\"hawkbitDevice\"",
     "measure": "HawkbitDevice001",
     "rawQuery": "SELECT BrakePedalPressure, BrakeActualPressure time FROM $__database.$__table WHERE time BETWEEN from_milliseconds($__from) AND from_milliseconds($__to)",
     "table": "\"ABS\""
    }
   ]
  },
  {
   "title": "Wheels_Speed (km/h)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "database": "\"hawkbitDevice\"",
     "measure": "HawkbitDevice001",
     "rawQuery": "SELECT Wheel1_Speed, Wheel2_Speed, Wheel3_Speed, Wheel4_Speed, time FROM $__database.$__table WHERE time BETWEEN from_milliseconds($__from) AND from_milliseconds($__to)",
     "table": "\"ABS\""
    }
   ]
  }
 ]
}