{
 "title": "Battery",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "BatteryAdded (%)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "database": "\"hawkbitDevice\"",
     "measure": "HawkbitDevice001",
     "rawQuery": "SELECT EnergyAdded, time FROM $__database.$__table WHERE time BETWEEN from_milliseconds($__from) AND from_milliseconds($__to)",
     "table": "\"Battery\""
    }
   ]
  },
  {
   "title": "BatteryTemperature (°C)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "database": "\"hawkbitDevice\"",
     "measure": "HawkbitDevice001",
     "rawQuery": "SELECT BatteryTemperature, time FROM $__database.$__table WHERE time BETWEEN from_milliseconds($__from) AND from_milliseconds($__to)",
     "table": "\"Battery\""
    }
   ]
  },
  {
   "title": "StateOfCharge (%)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "database": "\"hawkbitDevice\"",
     "measure": "HawkbitDevice001",
     "rawQuery": "SELECT \"StateOfCharge\" FROM $__database.$__table WHERE time BETWEEN from_milliseconds($__from) AND from_milliseconds($__to)",
     "table": "\"Battery\""
    }
   ]
  }
 ]
}