{
 "title": "Engine",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "BrakeRegenerationEfficiency (kW)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "database": "\"hawkbitDevice\"",
     "measure": "HawkbitDevice001",
     "rawQuery": "SELECT BrakeRegenerationEfficiency, time FROM $__database.$__table WHERE time BETWEEN from_milliseconds($__from) AND from_milliseconds($__to)",
     "table": "\"Engine\""
    }
   ]
  },
  {
   "title": "AcelleratorPedalPosition °",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "database": "\"hawkbitDevice\"",
     "measure": "HawkbitDevice001",
     "rawQuery": "SELECT AcelleratorPedalPosition, time FROM $__database.$__table WHERE time BETWEEN from_milliseconds($__from) AND from_milliseconds($__to)",
     "table": "\"Engine\""
    }
   ]
  },
  {
   "title": "AccelerationEfficiency (kW)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "database": "\"hawkbitDevice\"",
     "measure": "HawkbitDevice001",
     "rawQuery": "SELECT AccelerationEfficiency, time FROM $__database.$__table WHERE time BETWEEN from_milliseconds($__from) AND from_milliseconds($__to)",
     "table": "\"Engine\""
    }
   ]
  },
  {
   "title": "RPM",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "\"hawkbitDevice\"",
     "measure": "HawkbitDevice001",
     "rawQuery": "SELECT RPM FROM $__database.$__table WHERE time BETWEEN from_milliseconds($__from) AND from_milliseconds($__to)",
     "table": "\"Engine\""
    }
   ]
  }
 ]
}