version: '3'

services:

  
  rabbitmq:
    image: 'rabbitmq:3-management'
    restart: always
    ports:
      - '15672:15672'
      - '5672:5672'
    labels:
      NAME: 'rabbitmq'

  
  mysql:
    image: 'mysql:8.0'
    environment:
      MYSQL_DATABASE: 'hawkbit'
      # MYSQL_USER: 'root' is created by default in the container for mysql 8.0+
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
    restart: always
    ports:
      - '3306:3306'
    labels:
      NAME: 'mysql'

  
  hawkbit:
    image: 'hawkbit/hawkbit-update-server:latest-mysql'
    environment:
      - 'SPRING_DATASOURCE_URL=jdbc:mariadb://mysql:3306/hawkbit'
      - 'SPRING_RABBITMQ_HOST=rabbitmq'
      - 'SPRING_RABBITMQ_USERNAME=guest'
      - 'SPRING_RABBITMQ_PASSWORD=guest'
      - 'SPRING_DATASOURCE_USERNAME=root'
      - 'HAWKBIT_ARTIFACT_URL_PROTOCOLS_DOWNLOAD-HTTP_HOSTNAME=[server_ip_address]'
      - 'HAWKBIT_ARTIFACT_URL_PROTOCOLS_DOWNLOAD-HTTP_IP=[server_ip_address]'
    restart: always
    ports:
      - '8080:8080'
    volumes:
      - ./application.properties:/opt/hawkbit/application.properties
    labels:
      NAME: 'hawkbit'