This is makeindex, version 2.16 [MiKTeX 24.1].
Scanning style file ./thesis.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file thesis.acn....done (509 entries accepted, 0 rejected).
Sorting entries.......done (5134 comparisons).
Generating output file thesis.acr....done (222 lines written, 0 warnings).
Output written in thesis.acr.
Transcript written in thesis.alg.
