This is makeindex, version 2.16 [MiKTeX 24.1].
Scanning style file ./thesis.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file thesis.acn....done (174 entries accepted, 0 rejected).
Sorting entries.....done (1642 comparisons).
Generating output file thesis.acr....done (60 lines written, 0 warnings).
Output written in thesis.acr.
Transcript written in thesis.alg.
